#!/usr/bin/env sh 
#
# -*- mode: shell-script; fill-column: 75; comment-column: 50; -*-
#
# Copyright (c) 2013 Ralph Allan Rice <ralph.rice@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

SCRIPT=$(basename "${0}")

show_usage() {
   echo "Usage: ${1} [OPTIONS]" 1>&2 
}

show_help() {
    show_usage "${1}"
    cat 1>&2 <<-HELPDOC

Tokens all lines from standard input and print
each token to standard output one token per line.

Options:
       -h       Shows this help message.

HELPDOC
}

# Parse options
while getopts ":h" OPTION; do
    case ${OPTION} in
	h)
            show_help
	    exit 1
	    ;;
	?) 
	    echo "${SCRIPT}: invalid option -- ${OPTARG}" 1>&2
	    show_usage "${SCRIPT}"
	    echo "Try '${SCRIPT} -h' for more information."
	    exit 1
	    ;;
    esac
done

AWK="$(which awk)"

exec ${AWK} '
{
  for ( i = 1; i <= NF; i++ ) {
      print $i
  }
}' "$@"


